# Generated by Django 4.1.8 on 2023-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_alter_character_character_xp_alter_character_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
