# Generated by Django 4.1.8 on 2023-05-07 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0005_task_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
    ]
