# Generated by Django 4.1.9 on 2023-06-07 17:24

from django.db import migrations, models
import djangoapps.social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=djangoapps.social.models.profile_image_file_path),
        ),
    ]
